[package]
name    = "stspin220"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-embedded.com>"]
edition = "2018"

description = "Driver crate for the STSPIN220 stepper motor driver"
repository  = "https://github.com/braun-embedded/step-dir"
license     = "0BSD"
keywords    = ["step-dir", "stepper", "motor", "driver", "pololu"]
categories  = ["embedded", "hardware-support", "no-std", "science::robotics"]


[dependencies]
embedded-hal  = "1.0.0-alpha.1"
embedded-time = "0.10.0"
