# If adding a new driver, please try to keep the entries alphabetized! :)

[[drivers]]
name = "drv8825"
product_url = "https://www.ti.com/product/DRV8825"
pololu_url = "https://www.pololu.com/category/154/"

[[drivers]]
name = "stspin220"
product_url = "https://www.st.com/en/motor-drivers/stspin220.html"
pololu_url = "https://www.pololu.com/category/260/"
