name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cortex-M0+ target for test stand
      run: |
        rustup target install thumbv6m-none-eabi
    - name: Install cargo-task
      run: |
        cargo install cargo-task
    - name: Run build script
      run: ./scripts/build.sh
